version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"